# Generated by Django 6.1 on 2026-08-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(help_text='Emoji, ex. 🤝', max_length=10)),
                ('titre', models.CharField(max_length=150)),
                ('accroche', models.CharField(blank=True, help_text='Phrase courte visible sur la carte', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, help_text='Programme au format PDF ou Word (facultatif)', null=True, upload_to='activites/')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifiant technique, ex. « adidogome »', unique=True)),
                ('type', models.CharField(choices=[('Paroisse', 'Paroisse'), ('Quasi-Paroisse', 'Quasi-Paroisse'), ('Station secondaire', 'Station secondaire'), ('Sanctuaire', 'Sanctuaire')], max_length=30)),
                ('vocable', models.CharField(help_text='Ex. « Marie Mère du Rédempteur »', max_length=150)),
                ('lieu', models.CharField(max_length=100)),
                ('cure', models.CharField(blank=True, max_length=150)),
                ('recteur', models.CharField(blank=True, max_length=150)),
                ('responsable_nom', models.CharField(blank=True, max_length=150)),
                ('responsable_tel', models.CharField(blank=True, max_length=30)),
                ('localisation', models.CharField(blank=True, help_text='Texte libre affiché dans la fiche', max_length=255)),
                ('carte_url', models.URLField(blank=True, help_text='Lien de partage Google Maps précis (facultatif)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Communauté',
                'verbose_name_plural': 'Communautés',
                'ordering': ['type', 'vocable'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traitee', models.BooleanField(default=False, help_text='Cochée une fois le candidat recontacté')),
                ('paroisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='site_dlo3.communaute')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures (Rejoindre les servants)',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
