# Generated by Django 6.1 on 2026-08-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_dlo3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('montant', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('moyen_paiement', models.CharField(choices=[('Yas', 'Yas (Mixx by Yas)'), ('Flooz', 'Flooz (T-Money)'), ('Espèces', 'Espèces'), ('Autre', 'Autre')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('confirme', models.BooleanField(default=False, help_text='Cochée une fois la réception du don vérifiée')),
                ('paroisse', models.ForeignKey(blank=True, help_text='Facultatif', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='site_dlo3.communaute')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.DeleteModel(
            name='Candidature',
        ),
    ]
