# Generated by Django 6.1 on 2026-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_dlo3', '0002_don_delete_candidature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField()),
                ('titre', models.CharField(max_length=200)),
                ('extrait', models.CharField(help_text='Court résumé visible dans la liste', max_length=300)),
                ('contenu', models.TextField(help_text="Texte complet, affiché au clic sur l'article")),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
